### ISSUE TITLE
Hyper Key remap

### ISSUE THREAD

**Issue by abayomi185** [rossmacarthur/kb-remap#1]
Hi, Is it possible to do a hyper-key remap using this? Or multiple keys to a single key remap?

**Comment by rossmacarthur** [comment]
Sorry, this tool can only map from a single key. As far as a I know there is no way to do multi-key remaps without having an app running as a service and listening to key presses. This tool just simply applies settings as the USB HID level using hidutil. Maybe try [Karabiner-Elements](https://karabiner-elements.pqrs.org/).
