### ISSUE TITLE
Suggesting fluffing up a bit the doco

### ISSUE THREAD

**Issue by keyle** [rossmacarthur/kb-remap#2]
This is a great little project and I'm using it at the moment. Thank you for that.

One of thing I had trouble with was finding out the name of the keys - for example, there is no information about Function keys like F13 (unless I missed it).

I just would like to point out this website https://hidutil-generator.netlify.app that had an easy way to extract the raw values such as `0x700000068` and I can only suggest that somehow you document those somewhere or refer to a page that contains those?

thanks again.

**Comment by keyle** [comment]
Actually it's open source and the list of keys is there
https://github.com/amarsyla/hidutil-key-remapping-generator/blob/master/src/helpers/keys.js

HTH

**Comment by rossmacarthur** [comment]
Hi @keyle, thanks for the suggestion. I have added the function keys to the README. In addition I have added F1-F24 as aliases so you can now do the following:

```sh
kb-remap --map capslock:f3
```

This is available in 0.3.0
